[gcp_service_account]
type = "service_account"
project_id = "neuro-preconsulta-app"
private_key_id = "c536a7ca653b54943b19334d2aa6c0ad74d06336"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDBRviacUH1Lxbh
2fjjNzDeNbQ0Xl6MxGJoJtOGuIZFJ6+zrPIjB3PESPNZlKNL/Pq/57sw8wrNgTB3
ENNt6DewioepYFy6hDFg5GwIF1GcBF0cgVmmxx8po+TBwpGsFuluygdVR0oxsHcX
mxbTv5yR1l0BuLx9oWCwRjvYc8mnda3tSZVoIdB526knmkZWpEIHu4e9yiJJvo9T
nK/2MXLsig+36JMs8xroswDOAQ3JrC1NxnraNZCyROwuNYhMtKS5ABPdM+IKkZ7w
9zlhGzCO0mu1ng60jZBHJ25gp0Y8C4m6Zwn4PNgEIjKcOby+JT3mY6Ahcs4u7Ohq
mGpRHwIrAgMBAAECggEAHl8C+m8+WG3hivSlRJHL+bm3VdytFN0DQwSJjAumUGr6
aXc4HBhesQMZolkAtBR5E/uGZxxkn9hjf5eYRxa3huQDNLLHaikTAqZs8h81RsP0
xwxDGeRZBEJp1FIOcVwEVdF6B4Tf/CDpBepBUwgywplMcinPt291cchc58LXdvB4
0pyWh2itEuaEdEH2gxyL1bWJEj9kDkmqimYj9nLCvKhlZAxEVeEdiJBel7CWRtsj
4X2KOuEsg+tK05AH81JlxOhuc/OFknq7wqwsNLzjb1oVpc3wJSFeOXMLK1/4xXla
xLppKsODr6mcBokC/kCP3rAAxckPSm9sksYJKNwKUQKBgQD/BibtuodoJUyWLbKb
0UvRc/WsC3s7pakwy965GpSuBZlV1EyJ5csgD3NBY0UElnJc87kM/swpjpweIxGn
GhSvzaMxmsd3EDU/K4CvP1SZkyzNEOfEjeJP3uU04KaVMNfWHlNLtlazZbGx4YUt
Z11Lz32mBMWGSrP9d6YfC7s7UwKBgQDCBFNTAJNLWQCLOuhVr4U6RZnBrvc3xSkL
d+xoR8UTmgZxX9obPRgJDxx8gUSxDsxE/P0e5XpFnH4WgESlmFpxLcvI4tf3ldWN
hGsoTt/zBxPCSwiFwGFnskOEuCmfFb0hG9yCrQFRkzZzHrFwgg3RzwtPp65OcRoX
2L0mAK0ayQKBgQDeZz0X4a4o8y5hYiT7ooFefqRnj/O+xvBQL9tizn2Pbi6VHXpK
YG7O3OqEwc/0+kduLNbbMHJYY5he5/KDKkmUL9/8aKE/gpENMCEftDlRXXqas/2L
+ri9MwPtI2Xjgh8ZCoVV6ASgmzVmjeiY+iXw8VkAqfSg8xEZIXlsZcy5JQKBgBoq
ByqcW0DAAejEyuwzPV48YJ3UAJbOydg4FfOCKjuYe+HyMTGXLZSbKxZHQII4Iqfz
DheKjtCwZ/iU160VPK0ipeazYLiMxj3Na74F1QGrJKkBAWc4KGqZia1uQH6pqdW7
MiOVPSZJGgCwVPF9OGvg5f+Z91GwwvoQSoHDeZSxAoGBAMah2GRAdgdlMktUt0ay
mnUB/IcGJpWxUk+SST2vwsTAL8CW0Q4apdJxsUbpmpumx0p9nTdqv+dgdQPpatX4
AZDw7EES9Q5zbC6TuX3psaGmLPUJaylkaecxU14ECYqCeNu7J+W42MRZb+A+2WD9
UccjtcQDGxSSP0Kob+amEi65
-----END PRIVATE KEY-----"""
client_email = "sheets-access@neuro-preconsulta-app.iam.gserviceaccount.com"
client_id = "112549112663939802745"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-access@neuro-preconsulta-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
